### ISSUE TITLE
Allow set data to expire

### ISSUE THREAD

**Issue by Tails** [CodeSteak/Nuummite#4]
We could build a Rails-like persistent value cache if we could set a value with an expiration date (seconds). For example, I want to cache a JSON API response for 15mins when a iteratively run specs.

**Comment by CodeSteak** [comment]
Hey,
very interesting Idea! For a cache you may want to look for something like Redis (using AOF persistence logs) or a database designed for this purpose, you will get Way better performance. I think it would be a bit out of scope for this project.
